/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WsImport } from './routes/ws'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const WsRoute = WsImport.update({
  id: '/ws',
  path: '/ws',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ws': {
      id: '/ws'
      path: '/ws'
      fullPath: '/ws'
      preLoaderRoute: typeof WsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ws': typeof WsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ws': typeof WsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ws': typeof WsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ws'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ws'
  id: '__root__' | '/' | '/ws'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WsRoute: typeof WsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WsRoute: WsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ws"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ws": {
      "filePath": "ws.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
